
import React from 'react';
import { 
  LayoutDashboard, 
  GraduationCap, 
  HardDrive, 
  FileCheck, 
  ShieldAlert, 
  Star, 
  MessageSquareWarning, 
  Settings,
  UserCircle,
  Mail,
  CreditCard,
  Database,
  Globe,
  Users,
  Award,
  BookOpen,
  ClipboardList,
  CloudLightning,
  PhoneCall,
  Zap,
  Library,
  Scale,
  Search
} from 'lucide-react';
import { AppView, Faculty, UniversityService, Professor } from './types';

export const FACULTIES: Faculty[] = [
  { id: 'med', name: 'Faculty of Medicine', nameAr: 'كلية الطب البشري', code: 'FOM', icon: 'Stethoscope', description: 'Healthcare education.', descriptionAr: 'رائدة في التعليم الطبي.' },
  { id: 'eng', name: 'Faculty of Engineering', nameAr: 'كلية الهندسة', code: 'FOE', icon: 'Cpu', description: 'Innovation and design.', descriptionAr: 'التميز في الابتكار التكنولوجي.' },
  { id: 'pharma', name: 'Faculty of Pharmacy', nameAr: 'كلية الصيدلة', code: 'FOP', icon: 'Pill', description: 'Drug development.', descriptionAr: 'علوم صيدلانية متقدمة.' },
  { id: 'cs', name: 'Faculty of Computer Science', nameAr: 'كلية الحاسبات والمعلومات', code: 'FCS', icon: 'Cpu', description: 'AI and Systems.', descriptionAr: 'بناء خبراء في الأمن السيبراني.' },
  { id: 'comm', name: 'Faculty of Commerce', nameAr: 'كلية التجارة', code: 'FOC', icon: 'Calculator', description: 'Business and accounting.', descriptionAr: 'تأهيل كوادر مهنية في المحاسبة.' },
  { id: 'dent', name: 'Faculty of Dentistry', nameAr: 'كلية طب الأسنان', code: 'FOD', icon: 'UserCheck', description: 'Oral healthcare.', descriptionAr: 'التميز في جراحة الفم والأسنان.' },
];

export const PROFESSORS: Professor[] = [
  { 
    id: '1', 
    name: 'Dr. Ahmed Ibrahim', 
    nameAr: 'د. أحمد إبراهيم', 
    title: 'Professor of Software Architecture', 
    titleAr: 'أستاذ هندسة البرمجيات', 
    facultyId: 'cs', 
    department: 'Software Engineering',
    departmentAr: 'هندسة البرمجيات',
    specialization: 'Large Scale Systems',
    specializationAr: 'الأنظمة واسعة النطاق',
    email: 'a.ibrahim@znu.edu.eg',
    bio: 'Leading expert in digital transformation and cloud architectures with 20 years of experience.',
    bioAr: 'خبير رائد في التحول الرقمي وبنية الحوسبة السحابية مع خبرة تمتد لـ 20 عاماً.',
    officeHours: 'Mon, Wed: 10:00 AM - 12:00 PM',
    officeHoursAr: 'الاثنين، الأربعاء: 10:00 ص - 12:00 م',
    courses: ['CS401 Software Engineering II', 'CS403 Cloud Computing'],
    coursesAr: ['هندسة برمجيات 2', 'الحوسبة السحابية'],
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop'
  },
  { 
    id: '2', 
    name: 'Prof. Sarah Mansour', 
    nameAr: 'أ.د. سارة منصور', 
    title: 'Head of Mechatronics', 
    titleAr: 'رئيس قسم الميكاترونكس', 
    facultyId: 'eng', 
    department: 'Mechatronics Engineering',
    departmentAr: 'هندسة الميكاترونكس',
    specialization: 'Robotic Systems',
    specializationAr: 'الأنظمة الروبوتية',
    email: 's.mansour@znu.edu.eg',
    bio: 'Dedicated to advancing robotics and automation research within the national university context.',
    bioAr: 'مكرسة لتطوير أبحاث الروبوتات والأتمتة في سياق الجامعات الأهلية.',
    officeHours: 'Sun, Tue: 01:00 PM - 03:00 PM',
    officeHoursAr: 'الأحد، الثلاثاء: 01:00 م - 03:00 م',
    courses: ['ENG305 Control Systems', 'ENG410 Robotics'],
    coursesAr: ['أنظمة التحكم', 'الروبوتات'],
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop'
  },
  { 
    id: '3', 
    name: 'Dr. Mahmoud El-Sayed', 
    nameAr: 'د. محمود السيد', 
    title: 'Consultant Surgeon', 
    titleAr: 'استشاري جراحة', 
    facultyId: 'med', 
    department: 'Clinical Surgery',
    departmentAr: 'الجراحة الإكلينيكية',
    specialization: 'Laparoscopic Surgery',
    specializationAr: 'جراحة المناظير',
    email: 'm.elsayed@znu.edu.eg',
    bio: 'Specialist in minimally invasive surgical techniques and medical education.',
    bioAr: 'متخصص في تقنيات الجراحة طفيفة التوغل والتعليم الطبي.',
    officeHours: 'Daily: 08:00 AM - 10:00 AM',
    officeHoursAr: 'يومياً: 08:00 ص - 10:00 ص',
    courses: ['MED201 Clinical Anatomy', 'MED405 General Surgery'],
    coursesAr: ['التشريح الإكلينيكي', 'الجراحة العامة'],
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop'
  }
];

export const SERVICES: UniversityService[] = [
  { 
    id: 'ekb', 
    title: 'Egyptian Knowledge Bank', 
    titleAr: 'بنك المعرفة المصري', 
    externalUrl: 'https://www.ekb.eg',
    description: 'Access digital library.', 
    descriptionAr: 'الوصول إلى أكبر مكتبة رقمية بحثية.', 
    category: 'Academic', 
    status: 'Available', 
    icon: 'Library',
    color: 'text-amber-600'
  },
  { 
    id: 'staff_serv', 
    title: 'Staff Services', 
    titleAr: 'خدمات أعضاء هيئة التدريس', 
    description: 'Faculty management.', 
    descriptionAr: 'البوابة الموحدة للهيئة الأكاديمية.', 
    category: 'Administrative', 
    status: 'Available', 
    icon: 'Users',
    color: 'text-blue-600'
  },
  { 
    id: 'staff_pay', 
    title: 'Staff Payment Platform', 
    titleAr: 'منصة خدمات الدفع لأعضاء هيئة التدريس', 
    description: 'Financial services for staff.', 
    descriptionAr: 'إدارة المستحقات والمدفوعات الإلكترونية.', 
    category: 'Financial', 
    status: 'Available', 
    icon: 'CreditCard',
    color: 'text-emerald-600'
  },
  { 
    id: 'staff_mail', 
    title: 'Staff Email', 
    titleAr: 'بريد أعضاء هيئة التدريس الالكتروني', 
    description: 'Institutional email.', 
    descriptionAr: 'منصة التواصل الرسمي للموظفين.', 
    category: 'Administrative', 
    status: 'Available', 
    icon: 'Mail',
    color: 'text-rose-500'
  },
  { 
    id: 'stu_portal', 
    view: AppView.PROFILE,
    title: 'Student Services Portal', 
    titleAr: 'بوابة الخدمات الطلابية الكود الجامعي', 
    description: 'Personal records.', 
    descriptionAr: 'مركز متابعة الطالب والبيانات الأساسية.', 
    category: 'Administrative', 
    status: 'Available', 
    icon: 'UserCircle',
    color: 'text-indigo-600'
  },
  { 
    id: 'expats', 
    title: 'Expat Management', 
    titleAr: 'إدارة الوافدين', 
    description: 'International student services.', 
    descriptionAr: 'خدمات الدعم للطلاب غير المصريين.', 
    category: 'Administrative', 
    status: 'Available', 
    icon: 'Globe',
    color: 'text-sky-500'
  },
  { 
    id: 'mis', 
    title: 'Unified MIS', 
    titleAr: 'نظم المعلومات الموحد', 
    description: 'Data management.', 
    descriptionAr: 'قواعد البيانات المركزية للجامعة.', 
    category: 'Administrative', 
    status: 'Available', 
    icon: 'Database',
    color: 'text-cyan-600'
  },
  { 
    id: 'results', 
    view: AppView.RESULTS,
    title: 'Student Results', 
    titleAr: 'نتائج الطلاب', 
    description: 'View grades.', 
    descriptionAr: 'عرض النتائج والتقديرات الفصلية.', 
    category: 'Academic', 
    status: 'Available', 
    icon: 'FileCheck',
    color: 'text-indigo-600'
  },
  { 
    id: 'stu_pay', 
    title: 'Student Payment Platform', 
    titleAr: 'منصة الدفع الالكتروني الطلابية', 
    description: 'Pay tuition online.', 
    descriptionAr: 'سداد الرسوم الدراسية والخدمات.', 
    category: 'Financial', 
    status: 'Available', 
    icon: 'CreditCard',
    color: 'text-emerald-700'
  },
  { 
    id: 'stu_mail', 
    title: 'Student Email', 
    titleAr: 'بريد الطالب الالكتروني', 
    description: 'Official student email.', 
    descriptionAr: 'البريد الجامعي الرسمي للطلاب.', 
    category: 'Administrative', 
    status: 'Available', 
    icon: 'Mail',
    color: 'text-violet-500'
  },
  { 
    id: 'elearning', 
    view: AppView.ELEARNING,
    title: 'E-Learning & E-Exams Unit', 
    titleAr: 'وحدة التعليم الإلكتروني والاختبارات الإلكترونية', 
    description: 'Online learning portal.', 
    descriptionAr: 'منصة التعلم عن بعد والامتحانات.', 
    category: 'Academic', 
    status: 'Available', 
    icon: 'Zap',
    color: 'text-blue-500'
  },
  { 
    id: 'surveys', 
    view: AppView.SURVEYS,
    title: 'Student Surveys', 
    titleAr: 'استبيانات الطلاب', 
    description: 'Provide feedback.', 
    descriptionAr: 'تقييم جودة التعليم والخدمات.', 
    category: 'Administrative', 
    status: 'Available', 
    icon: 'ClipboardList',
    color: 'text-blue-400'
  },
  { 
    id: 'research', 
    view: AppView.RESEARCH,
    title: 'Research Publishing Rewards', 
    titleAr: 'التقدم لمكافآت تشجيع النشر العلمي', 
    description: 'Apply for incentives.', 
    descriptionAr: 'منصة الباحثين للمكافآت السنوية.', 
    category: 'Academic', 
    status: 'Available', 
    icon: 'Award',
    color: 'text-amber-500'
  },
  { 
    id: 'alumni', 
    view: AppView.ALUMNI,
    title: 'Alumni Affairs', 
    titleAr: 'شؤون الخريجين', 
    description: 'Services for graduates.', 
    descriptionAr: 'استخراج الشهادات وخدمات الخريجين.', 
    category: 'Administrative', 
    status: 'Available', 
    icon: 'GraduationCap',
    color: 'text-purple-600'
  },
  { 
    id: 'gov_complaints', 
    externalUrl: 'https://www.shakwa.eg',
    title: 'Unified Gov Complaints 16528', 
    titleAr: 'منظومة الشكاوى الحكومية الموحدة 16528', 
    description: 'Official government portal.', 
    descriptionAr: 'البوابة الرسمية الموحدة للشكاوى.', 
    category: 'Government', 
    status: 'Available', 
    icon: 'Scale',
    color: 'text-red-700'
  },
];

export const NAV_ITEMS = [
  { id: AppView.DASHBOARD, label: 'Home', labelAr: 'الرئيسية', icon: <LayoutDashboard size={20} /> },
  { id: AppView.FACULTIES, label: 'Faculties & Programs', labelAr: 'الكليات والبرامج', icon: <GraduationCap size={20} /> },
  { id: AppView.STAFF_DIRECTORY, label: 'Staff Directory', labelAr: 'دليل هيئة التدريس', icon: <Search size={20} /> },
  { id: AppView.DRIVE, label: 'Digital Library (Drive)', labelAr: 'المكتبة الرقمية (Drive)', icon: <HardDrive size={20} /> },
  { id: AppView.EVALUATION, label: 'Staff Evaluation', labelAr: 'هيئة التدريس والتقييم', icon: <Star size={20} /> },
  { id: AppView.EXAMS, label: 'Exams Center', labelAr: 'مركز الاختبارات', icon: <ShieldAlert size={20} /> },
  { id: AppView.RESULTS, label: 'Student Results', labelAr: 'نتائج الطلاب', icon: <FileCheck size={20} /> },
  { id: AppView.COMPLAINTS, label: 'Complaints Center', labelAr: 'مركز الشكاوى', icon: <MessageSquareWarning size={20} /> },
];
